# Validates compilation of RetroArch binary

name: RetroArch CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  linux: # Smoketest build using most restrictive compiler and default options
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install build-essential libxkbcommon-dev libx11-xcb-dev zlib1g-dev libfreetype6-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev nvidia-cg-toolkit nvidia-cg-dev libavcodec-dev libsdl2-dev libsdl-image1.2-dev libxml2-dev yasm flatpak flatpak-builder
          mkdir repo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: ./configure
      - name: Build
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak-builder builddir --repo=repo --install-deps-from=flathub --user --install --force-clean org.libretro.RetroArch.json
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: retroarch
          path: repo/          
